/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FranguinhoDaOnda.view;

import FranguinhoDaOnda.Produtos;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author sala302b
 */
public class CadastroProdutos extends javax.swing.JFrame {

    List<Produtos> produtos = new ArrayList<>();
    Produtos prd, prd1;

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroProdutos = new javax.swing.JPanel();
        prdCadastroLabel = new javax.swing.JLabel();
        prdCodigoLabel = new javax.swing.JLabel();
        prdCodigoTextField = new javax.swing.JTextField();
        prdNomeLabel = new javax.swing.JLabel();
        prdNomeTextField = new javax.swing.JTextField();
        prdPrecoLabel = new javax.swing.JLabel();
        prdPrecoTextField = new javax.swing.JTextField();
        prdbtCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastroProdutos.setMaximumSize(new java.awt.Dimension(520, 600));
        jPanelCadastroProdutos.setMinimumSize(new java.awt.Dimension(520, 600));
        jPanelCadastroProdutos.setPreferredSize(new java.awt.Dimension(520, 600));
        jPanelCadastroProdutos.setRequestFocusEnabled(false);

        prdCadastroLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        prdCadastroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prdCadastroLabel.setText("Cadastro de Produtos");

        prdCodigoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prdCodigoLabel.setText("Código:");

        prdNomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prdNomeLabel.setText("Nome:");

        prdPrecoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prdPrecoLabel.setText("Preço:");

        prdPrecoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prdPrecoTextFieldActionPerformed(evt);
            }
        });

        prdbtCadastrar.setText("Inserir");
        prdbtCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prdbtCadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroProdutosLayout = new javax.swing.GroupLayout(jPanelCadastroProdutos);
        jPanelCadastroProdutos.setLayout(jPanelCadastroProdutosLayout);
        jPanelCadastroProdutosLayout.setHorizontalGroup(
            jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroProdutosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(prdCodigoLabel)
                        .addComponent(prdNomeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(prdPrecoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prdCadastroLabel)
                    .addGroup(jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(prdPrecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prdCodigoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(prdNomeTextField))
                        .addComponent(prdbtCadastrar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelCadastroProdutosLayout.setVerticalGroup(
            jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prdCadastroLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prdCodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prdCodigoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prdNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prdNomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prdPrecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prdPrecoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prdbtCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prdbtCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prdbtCadastrarMouseClicked
        // INSERIR PRODUTOS
        prd = new Produtos(prdCodigoTextField.getText(), prdNomeTextField.getText(), prdPrecoTextField.getText());
        produtos.add(prd1);
    }//GEN-LAST:event_prdbtCadastrarMouseClicked

    private void prdPrecoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prdPrecoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prdPrecoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCadastroProdutos;
    private javax.swing.JLabel prdCadastroLabel;
    private javax.swing.JLabel prdCodigoLabel;
    private javax.swing.JTextField prdCodigoTextField;
    private javax.swing.JLabel prdNomeLabel;
    private javax.swing.JTextField prdNomeTextField;
    private javax.swing.JLabel prdPrecoLabel;
    private javax.swing.JTextField prdPrecoTextField;
    private javax.swing.JButton prdbtCadastrar;
    // End of variables declaration//GEN-END:variables
}
