/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FranguinhoDaOnda.view;

import FranguinhoDaOnda.Clientes;
import FranguinhoDaOnda.Enderecos;
import FranguinhoDaOnda.Telefones;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author sala302b
 */
public class CadastroClientes extends javax.swing.JFrame {

    List<Clientes> clientes = new ArrayList<>();
    Enderecos end;
    Telefones tel;
    Clientes cl1;

    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroClientes = new javax.swing.JPanel();
        clCadastroLabel = new javax.swing.JLabel();
        clPesquisarLabel = new javax.swing.JLabel();
        clPesquisarTextField = new javax.swing.JTextField();
        clbtPesquisar = new javax.swing.JButton();
        clCpfLabel = new javax.swing.JLabel();
        clCpfTextField = new javax.swing.JTextField();
        clNomeLabel = new javax.swing.JLabel();
        clNomeTextField = new javax.swing.JTextField();
        clTelefoneLabel = new javax.swing.JLabel();
        clTelefoneTextField = new javax.swing.JTextField();
        clCepLabel = new javax.swing.JLabel();
        clCepTextField = new javax.swing.JTextField();
        clRuaLabel = new javax.swing.JLabel();
        clRuaTextField = new javax.swing.JTextField();
        clBairroLabel = new javax.swing.JLabel();
        clBairroTextField = new javax.swing.JTextField();
        clNumeroLabel = new javax.swing.JLabel();
        clNumeroTextField = new javax.swing.JTextField();
        clComplementoLabel = new javax.swing.JLabel();
        clComplementoTextField = new javax.swing.JTextField();
        clbtCadastrar = new javax.swing.JButton();
        clbtAlterar = new javax.swing.JButton();
        clbtExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 430));
        setResizable(false);
        setSize(new java.awt.Dimension(520, 430));

        jPanelCadastroClientes.setMinimumSize(new java.awt.Dimension(520, 430));
        jPanelCadastroClientes.setPreferredSize(new java.awt.Dimension(520, 430));
        jPanelCadastroClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clCadastroLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        clCadastroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clCadastroLabel.setText("Cadastro de Clientes");
        jPanelCadastroClientes.add(clCadastroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 496, -1));

        clPesquisarLabel.setText("Pesquisar:");
        jPanelCadastroClientes.add(clPesquisarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 79, -1, -1));
        jPanelCadastroClientes.add(clPesquisarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 77, 400, -1));

        clbtPesquisar.setText("Pesquisar");
        clbtPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clbtPesquisarMouseClicked(evt);
            }
        });
        jPanelCadastroClientes.add(clbtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 102, -1, -1));

        clCpfLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clCpfLabel.setText("CPF:");
        jPanelCadastroClientes.add(clCpfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, 64, -1));
        jPanelCadastroClientes.add(clCpfTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 163, 400, -1));

        clNomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clNomeLabel.setText("Nome:");
        jPanelCadastroClientes.add(clNomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 190, 64, -1));
        jPanelCadastroClientes.add(clNomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 188, 400, -1));

        clTelefoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clTelefoneLabel.setText("Telefone:");
        jPanelCadastroClientes.add(clTelefoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 215, 64, -1));
        jPanelCadastroClientes.add(clTelefoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 213, 400, -1));

        clCepLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clCepLabel.setText("CEP:");
        jPanelCadastroClientes.add(clCepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 252, 64, -1));
        jPanelCadastroClientes.add(clCepTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 250, 400, -1));

        clRuaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clRuaLabel.setText("Rua:");
        jPanelCadastroClientes.add(clRuaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 277, 64, -1));
        jPanelCadastroClientes.add(clRuaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 275, 400, -1));

        clBairroLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clBairroLabel.setText("Bairro:");
        jPanelCadastroClientes.add(clBairroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 302, 64, -1));
        jPanelCadastroClientes.add(clBairroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 300, 400, -1));

        clNumeroLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clNumeroLabel.setText("Numero:");
        jPanelCadastroClientes.add(clNumeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 327, 64, -1));
        jPanelCadastroClientes.add(clNumeroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 325, 400, -1));

        clComplementoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clComplementoLabel.setText("Complemento:");
        jPanelCadastroClientes.add(clComplementoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 352, -1, -1));
        jPanelCadastroClientes.add(clComplementoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 350, 400, -1));

        clbtCadastrar.setText("Inserir");
        clbtCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clbtCadastrarMouseClicked(evt);
            }
        });
        jPanelCadastroClientes.add(clbtCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 381, -1, -1));

        clbtAlterar.setText("Alterar");
        clbtAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clbtAlterarMouseClicked(evt);
            }
        });
        jPanelCadastroClientes.add(clbtAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 381, -1, -1));

        clbtExcluir.setText("Excluir");
        clbtExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clbtExcluirMouseClicked(evt);
            }
        });
        jPanelCadastroClientes.add(clbtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 381, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clbtPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clbtPesquisarMouseClicked
        // PESQUISAR USUÁRIO
        boolean pes = clientes.contains(cl1);
        if (clientes.contains(cl1)) {
            // Enderecos(clCepTextField.getText(), clRuaTextField.getText(), clBairroTextField.getText());
            //  Telefones(clTelefoneTextField.getText());
            // Clientes(clCpfTextField.getText(), clNomeTextField.getText(), clNumeroTextField.getText(), clComplementoTextField.getText(), end, tel);

        } else {
            JOptionPane.showMessageDialog(null, "Usuário não existe no sistema.");}
    }//GEN-LAST:event_clbtPesquisarMouseClicked
    private void clbtAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clbtAlterarMouseClicked
        // ALTERAR USUÁRIO
    }//GEN-LAST:event_clbtAlterarMouseClicked

    private void clbtExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clbtExcluirMouseClicked
        // REMOVER USUÁRIO
    }//GEN-LAST:event_clbtExcluirMouseClicked

    private void clbtCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clbtCadastrarMouseClicked
        // INSERIR USUÁRIO
        end = new Enderecos(clCepTextField.getText(), clRuaTextField.getText(), clBairroTextField.getText());
        tel = new Telefones(clTelefoneTextField.getText());
        cl1 = new Clientes(clCpfTextField.getText(), clNomeTextField.getText(), clNumeroTextField.getText(), clComplementoTextField.getText(), end, tel);
        clientes.add(cl1);
    }//GEN-LAST:event_clbtCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clBairroLabel;
    private javax.swing.JTextField clBairroTextField;
    private javax.swing.JLabel clCadastroLabel;
    private javax.swing.JLabel clCepLabel;
    private javax.swing.JTextField clCepTextField;
    private javax.swing.JLabel clComplementoLabel;
    private javax.swing.JTextField clComplementoTextField;
    private javax.swing.JLabel clCpfLabel;
    private javax.swing.JTextField clCpfTextField;
    private javax.swing.JLabel clNomeLabel;
    private javax.swing.JTextField clNomeTextField;
    private javax.swing.JLabel clNumeroLabel;
    private javax.swing.JTextField clNumeroTextField;
    private javax.swing.JLabel clPesquisarLabel;
    private javax.swing.JTextField clPesquisarTextField;
    private javax.swing.JLabel clRuaLabel;
    private javax.swing.JTextField clRuaTextField;
    private javax.swing.JLabel clTelefoneLabel;
    private javax.swing.JTextField clTelefoneTextField;
    private javax.swing.JButton clbtAlterar;
    private javax.swing.JButton clbtCadastrar;
    private javax.swing.JButton clbtExcluir;
    private javax.swing.JButton clbtPesquisar;
    private javax.swing.JPanel jPanelCadastroClientes;
    // End of variables declaration//GEN-END:variables
}
