/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FranguinhoDaOnda.view;

import FranguinhoDaOnda.dao.PedidoDAO;
import FranguinhoDaOnda.model.Pedido;
import FranguinhoDaOnda.model.PedidoTableModel;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author sala302b
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
     private PedidoTableModel pedidoTableModel;
    
    public Pedidos() {
        initComponents();
        setarCaracteristicasTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pedidos = new javax.swing.JPanel();
        Pedido = new javax.swing.JLabel();
        pePesquisar = new javax.swing.JLabel();
        pePesquisarText = new javax.swing.JTextField();
        peBtPesquisar = new javax.swing.JButton();
        peSP = new javax.swing.JScrollPane();
        peJT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pedido.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        Pedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pedido.setText("Pedidos");

        pePesquisar.setText("Pesquisar:");

        peBtPesquisar.setText("Procurar");
        peBtPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peBtPesquisarMouseClicked(evt);
            }
        });

        peJT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        peSP.setViewportView(peJT);

        javax.swing.GroupLayout PedidosLayout = new javax.swing.GroupLayout(Pedidos);
        Pedidos.setLayout(PedidosLayout);
        PedidosLayout.setHorizontalGroup(
            PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PedidosLayout.createSequentialGroup()
                        .addComponent(pePesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PedidosLayout.createSequentialGroup()
                                .addComponent(pePesquisarText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peBtPesquisar))
                            .addComponent(peSP, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PedidosLayout.setVerticalGroup(
            PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pedido)
                .addGap(18, 18, 18)
                .addGroup(PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pePesquisarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peBtPesquisar)
                    .addComponent(pePesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // PREPARAR TABELAS
    private void setarCaracteristicasTabela() {
        //seleção para a linha inteira
        this.peJT.setCellSelectionEnabled(false);
        this.peJT.setRowSelectionAllowed(true);
        //selecionar apenas uma linha
        this.peJT.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    private void peBtPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peBtPesquisarMouseClicked
        // PESQUISAR PEDIDOS
        PedidoDAO pedidodao = new PedidoDAO();
        // Terminar!
        //ArrayList<Pedido> pedidos = pedidodao.getlist(pePesquisarText.getText());
        //pedidoTableModel = new PedidoTableModel(pedidos);
        peJT.setModel(pedidoTableModel);
    }//GEN-LAST:event_peBtPesquisarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pedido;
    private javax.swing.JPanel Pedidos;
    private javax.swing.JButton peBtPesquisar;
    private javax.swing.JTable peJT;
    private javax.swing.JLabel pePesquisar;
    private javax.swing.JTextField pePesquisarText;
    private javax.swing.JScrollPane peSP;
    // End of variables declaration//GEN-END:variables
}
